[package]
name = "bevy_xpbd"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.7.0"
parry2d = "0.9.0"
console_error_panic_hook = "0.1"

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1

[[example]]
name = "move_marbles"
path = "examples/2d/move_marbles.rs"
