[package]
name = "bevy_xpbd_derive"
version = "0.1.0"
edition = "2021"
description = "Provides derive implementations for Bevy XPBD"
repository = "https://github.com/Jondolf/bevy_xpbd"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "2.0"
