[package]
name = "bevy_xpbd_2d"
version = "0.1.0"
edition = "2021"

[features]
default = [ "2d" ]
2d = []

[lib]
name = "bevy_xpbd_2d"
path = "../../src/lib.rs"
required-features = [ "2d" ]

[dependencies]
bevy = "0.7.0"
parry2d = { version = "0.9.0" }
nalgebra = { version = "0.31.0", features = [ "convert-glam020" ] }
console_error_panic_hook = "0.1"
web-sys = "0.3.57"
cfg-if = "1.0.0"
